export default async function DefaultLayout({ children, meta, pages }) {
  return (
    <html>
      <head>
        <title>{meta.title}</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
      </head>
      <body className="mx-auto max-w-2xl w-full py-8 px-4">
        <header className="mb-8 pb-1 border-b border-gray-200">
          <h1 className="text-base sm:text-2xl font-bold my-sans">
            {meta.title}
          </h1>
          <nav className="mb-4">
            {pages.map((page) => {
              return (
                <a key={page.href} href={page.href} className="mr-2 text-sm">
                  {page.meta.title}
                </a>
              );
            })}
          </nav>
        </header>
        <main>{children}</main>
        <footer className="mt-8 border-t border-gray-200 py-4 text-center">
          Generated by docship
        </footer>
      </body>
    </html>
  );
}
